---
name: BootstrapForm
---
UncleCheese\BootstrapForms\BootstrapForm:
  bootstrap_included: true
  jquery_included: true
  bootstrap_form_included: true
  bootstrap_select_included: true
  inline_fields:
    - SilverStripe\Forms\CheckboxField
    - SilverStripe\Forms\FormAction
SilverStripe\Forms\FormField:
  extensions:
    - UncleCheese\BootstrapForms\BootstrapFormField
SilverStripe\Forms\TextField:
  extensions:
    - UncleCheese\BootstrapForms\BootstrapTextField
SilverStripe\Forms\OptionsetField:
  extensions:
    - UncleCheese\BootstrapForms\BootstrapOptionsetField
SilverStripe\Forms\FormAction:
  extensions:
    - UncleCheese\BootstrapForms\BootstrapFormAction
SilverStripe\Forms\TextareaField:
  extensions:
    - UncleCheese\BootstrapForms\BootstrapTextField
SilverStripe\Forms\FieldList:
  extensions:
    - UncleCheese\BootstrapForms\BootstrapFieldList
SilverStripe\Forms\CheckboxSetField:
  extensions:
    - UncleCheese\BootstrapForms\BootstrapCheckboxSetField
SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\MemberAuthenticator\MemberLoginForm:
    class: UncleCheese\BootstrapForms\BootstrapMemberLoginForm
---
only:
  moduleexists: userforms
---
SilverStripe\UserForms\Control\UserDefinedFormController:
  extensions:
    - UncleCheese\BootstrapForms\BootstrapUserForm
